apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-nginx-deployment
  labels:
    app: webapp-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-nginx
  template:
    metadata:
      labels:
        app: webapp-nginx
    spec:
      containers:
      - name: webapp-nginx
        image: megatestacr.azurecr.io/webapp
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
