apiVersion: v1
kind: Service
metadata:
  name: webapp-loadbalancer-service
  labels:
    app: webapp-nginx
spec:
  selector:
    app: webapp-nginx
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
